### ISSUE TITLE
don't use `any`

### ISSUE THREAD

**Issue by MicahZoltu** [paulmillr/micro-web3#1]
https://github.com/paulmillr/micro-web3/blob/7ea40f0c5b7fe2de013eb835dea9a9c532dcc750/src/index.ts#L206

Use `unknown` here instead.  `any` in TS disables all type checking on the variable which is an easy way to shoot yourself in the foot.  The user can cast to `any` if they want to YOLO, but by default the user should be protected from foot guns, even when they are convenient.

**Comment by MicahZoltu** [comment]
Same with all of the contract methods in `src/contracts`, but in that case you can do far better than `unknown` since you actually know the required type pretty specifically.

**Comment by paulmillr** [comment]
@MicahZoltu full support for types had been added in 8f3b82c97f3601d9bf388156ba1ca3d49de7b835.

I will add some docs/JS tests asap and the package should be stable & ready to go after that.
